-- Database: TRANS_MADEIRA

-- DROP DATABASE "TRANS_MADEIRA";

CREATE DATABASE "TRANS_MADEIRA"
    WITH 
    OWNER = trans_madeira
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

GRANT ALL ON DATABASE "TRANS_MADEIRA" TO trans_madeira WITH GRANT OPTION;

GRANT ALL ON DATABASE "TRANS_MADEIRA" TO PUBLIC;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO trans_madeira WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO PUBLIC;

ALTER DEFAULT PRIVILEGES
GRANT USAGE, SELECT ON SEQUENCES TO trans_madeira WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
GRANT SELECT, USAGE ON SEQUENCES TO PUBLIC;

ALTER DEFAULT PRIVILEGES
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
GRANT EXECUTE ON FUNCTIONS TO trans_madeira WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
GRANT EXECUTE ON FUNCTIONS TO PUBLIC;

ALTER DEFAULT PRIVILEGES
GRANT USAGE ON TYPES TO postgres;

ALTER DEFAULT PRIVILEGES
GRANT USAGE ON TYPES TO trans_madeira WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
GRANT USAGE ON TYPES TO PUBLIC;

