-- SCHEMA: TRANSMADEIRA

-- DROP SCHEMA "TRANSMADEIRA" ;

CREATE SCHEMA "TRANSMADEIRA"
    AUTHORIZATION trans_madeira;

GRANT ALL ON SCHEMA "TRANSMADEIRA" TO trans_madeira WITH GRANT OPTION;

GRANT ALL ON SCHEMA "TRANSMADEIRA" TO PUBLIC;